import type { Product, Category } from '../types';

export const mockCategories: Category[] = [
  {
    id: 'c1',
    name: 'Ultra-Thin',
    slug: 'ultra-thin',
    description: 'Thin and light gaming laptops for maximum portability.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c2',
    name: 'Desktop Replacement',
    slug: 'desktop-replacement',
    description: 'Heavy and powerful laptops that replace a desktop.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c3',
    name: 'Budget Gaming',
    slug: 'budget-gaming',
    description: 'Affordable gaming laptops for entry-level gamers.',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Razer Blade 16',
    slug: 'razer-blade-16',
    description: 'The world\'s first dual-mode mini-LED display gaming laptop. Switch between 4K 120Hz and FHD+ 240Hz depending on your needs. Packed with an RTX 4090 and an i9 processor inside a sleek unibody aluminum chassis.',
    price: 3499.99,
    stock: 12,
    brand: 'Razer',
    model: 'Blade 16 2024',
    specs: {
      cpu: 'Intel Core i9-14900HX',
      gpu: 'NVIDIA GeForce RTX 4090 16GB',
      ram: '32GB DDR5 5600MHz',
      storage: '2TB PCIe 4.0 NVMe M.2 SSD',
      display: '16" Dual-Mode Mini-LED (4K 120Hz / FHD+ 240Hz)',
    },
    images: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1000&auto=format&fit=crop'],
    isActive: true,
    isFeatured: true,
    categoryId: 'c1',
    category: mockCategories[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    badge: 'Flagship'
  },
  {
    id: 'p2',
    name: 'ASUS ROG Zephyrus G14',
    slug: 'asus-rog-zephyrus-g14',
    description: 'Ultra-portable 14-inch gaming laptop that doesn\'t compromise on power. Features an incredible OLED display, an AMD Ryzen 9 processor, and an RTX 4070 in a chassis that weighs just 3.3 lbs.',
    price: 1999.99,
    stock: 25,
    brand: 'ASUS',
    model: 'GA403UI',
    specs: {
      cpu: 'AMD Ryzen 9 8945HS',
      gpu: 'NVIDIA GeForce RTX 4070 8GB',
      ram: '32GB LPDDR5X',
      storage: '1TB PCIe 4.0 NVMe SSD',
      display: '14" 3K OLED 120Hz (2880 x 1800)',
    },
    images: ['https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=1000&auto=format&fit=crop'],
    isActive: true,
    isFeatured: true,
    categoryId: 'c1',
    category: mockCategories[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    badge: 'Best Seller'
  },
  {
    id: 'p3',
    name: 'Lenovo Legion Pro 7i',
    slug: 'lenovo-legion-pro-7i',
    description: 'Peak performance machine designed for competitive gaming. Excellent thermal design and max TGP graphics options make this one of the fastest laptops on the market.',
    price: 2699.99,
    stock: 8,
    brand: 'Lenovo',
    model: '16IRX9',
    specs: {
      cpu: 'Intel Core i9-14900HX',
      gpu: 'NVIDIA GeForce RTX 4080 12GB (175W)',
      ram: '32GB DDR5 5600MHz',
      storage: '2TB (2x 1TB) Gen 4 SSD',
      display: '16" WQXGA 240Hz IPS (2560 x 1600)',
    },
    images: ['https://images.unsplash.com/photo-1611078489935-0cb964de46d6?q=80&w=1000&auto=format&fit=crop'],
    isActive: true,
    isFeatured: true,
    categoryId: 'c2',
    category: mockCategories[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    badge: 'Professional'
  },
  {
    id: 'p4',
    name: 'Alienware m18 R2',
    slug: 'alienware-m18-r2',
    description: 'A massive 18-inch screen desktop replacement that commands attention. Boasts unparalleled performance with top-tier components and advanced Cryo-tech cooling.',
    price: 3299.99,
    stock: 5,
    brand: 'Alienware',
    model: 'm18 R2',
    specs: {
      cpu: 'Intel Core i9-14900HX',
      gpu: 'NVIDIA GeForce RTX 4090 16GB',
      ram: '64GB DDR5 5200MHz',
      storage: '4TB RAID 0 PCIe SSD',
      display: '18" QHD+ 165Hz (2560 x 1600)',
    },
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1000&auto=format&fit=crop'],
    isActive: true,
    isFeatured: true,
    categoryId: 'c2',
    category: mockCategories[1],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Acer Nitro 17',
    slug: 'acer-nitro-17',
    description: 'A budget-friendly 17-inch gaming laptop that offers solid 1080p performance without breaking the bank.',
    price: 1199.99,
    stock: 45,
    brand: 'Acer',
    model: 'AN17-41',
    specs: {
      cpu: 'AMD Ryzen 7 7840HS',
      gpu: 'NVIDIA GeForce RTX 4050 6GB',
      ram: '16GB DDR5',
      storage: '1TB PCIe Gen4 SSD',
      display: '17.3" FHD 144Hz (1920 x 1080)',
    },
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop'],
    isActive: true,
    isFeatured: false,
    categoryId: 'c3',
    category: mockCategories[2],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    name: 'HP OMEN Transcend 14',
    slug: 'hp-omen-transcend-14',
    description: 'A stylish, ultra-portable gaming and creator laptop. Features an RGB keyboard with translucent keys and an OLED display.',
    price: 1599.99,
    stock: 18,
    brand: 'HP',
    model: '14-fb0000',
    specs: {
      cpu: 'Intel Core Ultra 9 185H',
      gpu: 'NVIDIA GeForce RTX 4060 8GB',
      ram: '32GB LPDDR5x',
      storage: '1TB Gen4 NVMe SSD',
      display: '14" 2.8K OLED 120Hz (2880 x 1800)',
    },
    images: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1000&auto=format&fit=crop'],
    isActive: true,
    isFeatured: true,
    categoryId: 'c1',
    category: mockCategories[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];